language: node_js

git:
  depth: false
  quiet: true

# https://pnpm.io/continuous-integration#travis
cache:
  npm: false
  directories:
    - "~/.pnpm-store"

_job_win: &job_windows
  os: windows
  env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
  before_install: choco install python

_job_linux: &job_linux
  os: linux

  # Node 16 requires Python >= 3.6 for compile addon，which is not exists in Xenial.
  dist: focal

jobs:
  include:
    - <<: *job_windows
      node_js: 14

    - <<: *job_windows
      node_js: 16

    - <<: *job_linux
      node_js: 14

    - <<: *job_linux
      node_js: 16

install:
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
  - pnpm config set store-dir ~/.pnpm-store
  - pnpm install -g node-gyp codecov
  - pnpm install --no-optional

before_script: node-gyp rebuild

script:
  - pnpm test:coverage
  - codecov

after_success: node script/prebuild.js pack

deploy:
  provider: releases
  skip_cleanup: true
  token: $GITHUB_TOKEN
  file_glob: true
  file: prebuilds/*
  on:
    tags: true
