name: Build

on:
  create:
    tags:
      - v*

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          check-latest: true

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/checkout@v2

      - run: npm i -g pnpm

      - run: pnpm install -g node-gyp

      - run: pnpm install

      - name: Build
        run: node-gyp rebuild

      - name: Package
        run: node script/prebuild.js pack

      - name: Upload prebuild binary
        uses: softprops/action-gh-release@v1
        with:
          files: prebuilds/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
