name: Test

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [14, 16]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - uses: actions/checkout@v2

      - name: Cache .pnpm-store
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Node deps
        run: |
          npm i -g pnpm
          pnpm i -g node-gyp codecov
          pnpm install

      - name: Build Addon
        run: node-gyp rebuild

      - name: Test
        run: pnpm test:coverage

      - name: Upload Coverage
        run: codecov
