name: Test

on: push

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [14, 16, 17]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - uses: actions/checkout@v3

      - name: Cache .pnpm-store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-node${{ matrix.node }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install Node deps
        run: |
          npm i -g pnpm
          pnpm i -g node-gyp

      - run: pnpm install
        env:
          NO_PREBUILD: true

      - name: Build Addon
        run: node-gyp rebuild

      # worker_threads needs js output
      - name: Test
        run: |
          pnpm run compile:ts
          pnpm run test:coverage

      - uses: codecov/codecov-action@v3
